
#include <iostream>
using namespace std;
 struct book
{
    string title;
    int publication_year;
    string author;
};



int main()
{




    book ob;
    ob.title="english";
    ob. publication_year=2010;
    ob. author="ABC PUBLICATION";

    cout<<"BOOK'S NAME - "<<    ob.title  <<endl;
    cout<<"PUBLICATION YEAR - "<<ob. publication_year  <<endl;
    cout<<"AUTHOR - "<<  ob. author <<endl;





}
